version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.346
    container_name: jenkins
    restart: always
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"